### ISSUE TITLE
lp_set_cmdline isn't in older libsmbclients

### ISSUE THREAD

**Issue by divad** [hamano/pysmbc#16]
Hi,

In the latest version of pysmbc, you use 'lp_set_cmdline' to set the client max protocol, however this call fails on RHEL6:

`ImportError: /usr/lib64/python2.6/site-packages/_smbc.so: undefined symbol: lp_set_cmdline`

I'm guessing this is because lp_set_cmdline isn't in Samba 3.6 (RHEL6 has 3.6.23-43).

The docs page says the minimum version of libsmbclient is 3.2, but it might be that a much later version (4.x?) is needed. Not sure!

**Comment by guettli** [comment]
We had the same issue here. Creating a wheel (compiling) worked, but importing the library failed with above exception. I agree, I think a newer libsmbclient is needed. I think it is strange that compiling the wheel works. But for me the issue is solved, we took a newer lib.

**Comment by hamano** [comment]
fixed, sorry for late response.
thanks.

**Comment by cziebuhr** [comment]
`smbc_option_set` doesn't seem to work here, because it only accepts a limited set of options and `client min/max protocol` is not contained. Btw, `smbc_setOptionProtocols` indicates it's able to set protocol per context, but it also only calls `lp_set_cmdline` with `client min/max protocol`, which acts globally. At least it works unless someone tries to use several context objects with different protocol settings.

**Comment by hamano** [comment]
@cziebuhr
Thank you for investigating.
I understand that there is no way to set the min/max protocol in libsmbc under 0.5.0.
I'll remove the smbc_option_set code.
